spring.application.name=HRApplication

#config database
###
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/do_an_se347?useSSL=true&requireSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
###

###
#config jwt
se347.jwt.base64-secret=${JWT_SECRET:changeme}
#expiration time in seconds (10 day)
se347.jwt.access-token-validity-in-seconds=864000
se347.jwt.refresh-token-validity-in-seconds=864000
#
###

#config upload file
###
# #default = 1MB
spring.servlet.multipart.max-file-size=50MB

# #default = 10 MB (form data)
spring.servlet.multipart.max-request-size=50MB
###

#re-config dev tool
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

#config pagination defaults
# Default page size.
spring.data.web.pageable.default-page-size=20
 # Maximum page size to be accepted.
spring.data.web.pageable.max-page-size=2000
#Index start at 1
spring.data.web.pageable.one-indexed-parameters=true

#config actuator
management.endpoints.web.exposure.include=health,info,metrics,env,beans,mappings
management.endpoint.health.show-details=when-authorized
management.health.defaults.enabled=true